create table if not exists "user"
(
	"id" integer generated by default as identity primary key,
	"group_id" integer,
	"version" integer default 0 not null,
	"name" varchar(20) not null,
	"password" varchar(50) not null,
	"state" integer default 0 not null
);